version: '3.8'

services:
  frontend:
    build:
      context: /frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - api

  api:
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:password@mysql:3306/test_db"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
