version: '3.7'

networks:
  app_network:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - app_network

  api:
    container_name: threeo-test-api
    build:
      context: ./api
      dockerfile: docker/Dockerfile
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://root:password@mysql:3306/test_db"
      CHOKIDAR_USEPOLLING: 'true'
      PORT: 5000
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    networks:
      - app_network

